let
    CombinedInventorySources=Table.Combine({#"On Hand",#"In Transit",RGA}),
    ZeroValues = Table.ReplaceValue(CombinedInventorySources,null,0,Replacer.ReplaceValue,{"Total On Hand", "Total In Transit", "Total Not Nettable"}),
    #"Grouped Rows" = Table.Group(ZeroValues, {"Item&Org", "New Item", "Org"}, {{"On Hand", each List.Sum([Total On Hand]), type nullable number}, {"In Transit", each List.Sum([Total In Transit]), type nullable number}, {"Not Nettable", each List.Sum([Total Not Nettable]), type nullable number}}),
    #"Added Custom" = Table.AddColumn(#"Grouped Rows", "Total Available", each let
invoh = [On Hand],
novih = [Not Nettable]
in 
if (invoh + novih) < 0 then 0 else (invoh + novih), Int64.Type),
    #"Reordered Columns" = Table.ReorderColumns(#"Added Custom",{"New Item", "Total Available", "In Transit", "Org", "Item&Org", "On Hand", "Not Nettable"}),
    #"Removed Columns" = Table.RemoveColumns(#"Reordered Columns",{"On Hand", "Not Nettable"}),
    #"Added Custom1" = Table.AddColumn(#"Removed Columns", "Total Inventory", each [Total Available] + [In Transit], Int64.Type)
in
    #"Added Custom1"