// Made by: Hazzard
let
    Src_SP=SharePoint.Files("https://nmca.sharepoint.com/sites/MASTER365/",[ApiVersion=15]),// Load files from SharePoint
    Filtr_XlsxAndName=Table.SelectRows(Src_SP, each Text.Contains([Name],"NMC All Reports Template") and Text.EndsWith([Extension],".xlsx")),// Keep only matching template .xlsx files
    Sort_ModifiedDesc=Table.Sort(Filtr_XlsxAndName,{{"Date modified",Order.Descending}}),// Sort newest file first
    TakeLatest=Table.FirstN(Sort_ModifiedDesc,1),// Keep most recent file only
    Xl=Excel.Workbook(TakeLatest{0}[Content],null,true),// Open workbook from latest file
    FirstSheet=Xl{0}[Data],// Get first sheet data
    Skip_Top4=Table.Skip(FirstSheet,4),// Remove top 4 header/metadata rows
    PromoteHdrs=Table.PromoteHeaders(Skip_Top4,[PromoteAllScalars=true]),// Promote first data row to headers
    Add_OrderClassification=Table.AddColumn(PromoteHdrs,"Order Classification", each let wj=try Text.From([#"WIP/JOB"]) otherwise "", st=try Text.From([MFG_ORDER_STATUS]) otherwise "" in if st="On Hold" then "Hold" else if Text.Contains(wj,"-S") then "Sample" else if List.AnyTrue({Text.Contains(wj,"EMR"),Text.Contains(wj,"PMR"),Text.Contains(wj,"MR"),Text.Contains(wj,"LAB")}) then "Prototype" else if Text.Contains(wj,"RWK") then "RWK" else if Text.Contains(wj,"Stage") then "Stage" else if Text.Contains(wj,"-") then "Master" else "Planning", type text),// Add classification (safe text coercion + typed)
    Rename_ForReadability=Table.RenameColumns(Add_OrderClassification,{{"DATE_RELEASED","Date Released"},{"ITEM_NUMBER","Item Number"},{"PRODUCTION_LINE","Production Line"},{"Stack Height","Stack"},{"Number Of Speeds","Speeds"},{"START_DATE","Start Date"},{"COMPLETION_DATE","Completion Date"},{"First_completion_date","1st Completion Date"},{"ATTRIBUTE1","Revised Schedule Date"},{"START_QUANTITY","Start Qty"},{"ITEM_TYPE","Item Type"},{"ATTRIBUTE3","ISO"},{"DESCRIPTION","Description"},{"MOTOR_TYPE","Motor Type"},{"MFG_ORDER_STATUS","Order Status"},{"ATTRIBUTE4","Comment"},{"INVENTORY_ITEM_STATUS_CODE","Item Status"},{"LAST_UPDATE_DATE","Last Updated Date"},{"DESCRIPTION_1","Oracle Load Type"},{"MFG_ORDER_TYPE","Order Type"},{"ORGANIZATION_NAME","Organization Name"},{"CLASSIFICATION","Classification"},{"CONSTRUCTION_MATERIAL","Construction Material"}}),// Rename columns exactly as provided
    TextCols={"WIP/JOB","Item Number","Production Line","Item Type","ISO","Description","Motor Type","Order Status","Comment","Item Status","Oracle Load Type","Order Type","Organization Name","Classification","Construction Material","Stack","Speeds","Order Classification"},// Define text columns for Null replacement
    ReplaceNulls_Text=Table.ReplaceValue(Rename_ForReadability,null,"Null",Replacer.ReplaceValue,TextCols),// Replace nulls with "Null" only in text columns
    Set_Types=Table.TransformColumnTypes(ReplaceNulls_Text,{{"Date Released",type date},{"WIP/JOB",type text},{"Item Number",type text},{"Production Line",type text},{"Stack",type text},{"Speeds",type text},{"Start Date",type date},{"Completion Date",type date},{"1st Completion Date",type date},{"Revised Schedule Date",type date},{"Remaining Qty",Int64.Type},{"Start Qty",Int64.Type},{"Item Type",type text},{"ISO",type text},{"Description",type text},{"Motor Type",type text},{"Order Status",type text},{"Comment",type text},{"Item Status",type text},{"Last Updated Date",type date},{"Oracle Load Type",type text},{"Order Type",type text},{"Organization Name",type text},{"Classification",type text},{"Construction Material",type text},{"Order Classification",type text}}),// Single consolidated type assignment
    Sort_ByDateReleased=Table.Sort(Set_Types,{{"Date Released",Order.Ascending}}),// Sort ascending by Date Released
    Filter_ItemNumberNotNull=Table.SelectRows(Sort_ByDateReleased, each let it=try Text.From([Item Number]) otherwise "" in not Text.Contains(it,"Null"))// Remove rows where Item Number contains "Null"
in
    Filter_ItemNumberNotNull
