let
    Sharepoint = SharePoint.Files("https://nmca.sharepoint.com/sites/MASTER365/", [ApiVersion = 15]),
    FolderColumns = Table.RemoveColumns(Sharepoint,{"Date accessed", "Date created", "Attributes"}),
    ReportsFolder = Table.SelectRows(FolderColumns, each Text.Contains([Folder Path], "/Reports/") and ([Extension] = ".xlsx")),
    DateSort = Table.Sort(ReportsFolder,{{"Date modified", Order.Descending}}),
    FileName = Table.SelectRows(DateSort, each Text.Contains([Name], "NMC_DFF")),
    LatestFile=Table.Max(FileName,"Date modified"),
    Import=Excel.Workbook(LatestFile[Content],null,true),
    ExcelSheet=Import{0}[Data],
    TopRows=Table.Skip(ExcelSheet,6),
    Headers = Table.PromoteHeaders(TopRows, [PromoteAllScalars=true]),
    Type = Table.TransformColumnTypes(Headers,{{"DATE_RELEASED", type date}, {"WIP/JOB", type text}, {"ITEM_NUMBER", type text}, {"PRODUCTION_LINE", type text}, {"START_DATE", type date}, {"COMPLETION_DATE", type date}, {"REVISED_SCHEDULE_DATE", type date}, {"DATE_COMPLETED", type datetime}, {"START_QTY", Int64.Type}, {"COMPLETED_QTY", Int64.Type}, {"REMAINING_QTY", Int64.Type}, {"ITEM_TYPE", type text}, {"ISO/SO", type text}, {"DESCRIPTION", type text}, {"MOTOR_TYPE", type text}, {"ORDER_STATUS", type text}, {"COMMENT", type text}, {"DESCRIPTION_1", type text}, {"MFG_ORDER_TYPE", type text}, {"ORGANIZATION_NAME", type text}}),
    OrderClass = Table.AddColumn(Type, "Order_Class", each let
        wip = if [#"WIP/JOB"] = null then "" else [#"WIP/JOB"],
        sts = if [DESCRIPTION_1] = null then "" else [DESCRIPTION_1],
        ost = if [ORDER_STATUS] = null then "" else [ORDER_STATUS]
    in
        if Text.Contains(wip, "-", Comparer.OrdinalIgnoreCase) then
            if Text.Contains(ost, "Hold", Comparer.OrdinalIgnoreCase) then "Hold Order"
            else if Text.Contains(wip, "MR", Comparer.OrdinalIgnoreCase) or Text.Contains(wip, "-S", Comparer.OrdinalIgnoreCase) or Text.Contains(sts, "Pre-pilot", Comparer.OrdinalIgnoreCase) or Text.Contains(sts, "Prototype", Comparer.OrdinalIgnoreCase) then "Eng Order"
            else if Text.Contains(wip, "RWK", Comparer.OrdinalIgnoreCase) then "Rework Order"
            else "Master Order"
        else
            "Planning Order",type text),
    ReplaceNull = Table.ReplaceValue(OrderClass,null,"Null",Replacer.ReplaceValue,{"DATE_RELEASED", "WIP/JOB", "ITEM_NUMBER", "PRODUCTION_LINE", "START_DATE", "COMPLETION_DATE", "REVISED_SCHEDULE_DATE", "DATE_COMPLETED", "START_QTY", "COMPLETED_QTY", "REMAINING_QTY", "ITEM_TYPE", "ISO/SO", "DESCRIPTION", "MOTOR_TYPE", "ORDER_STATUS", "COMMENT", "DESCRIPTION_1", "MFG_ORDER_TYPE", "ORGANIZATION_NAME", "Order_Class"}),
    RemoveColumns = Table.RemoveColumns(ReplaceNull,{"DESCRIPTION_1", "MFG_ORDER_TYPE", "ORGANIZATION_NAME"})
in
    RemoveColumns